language: ruby
cache: bundler
rvm:
 - 2.2.2
# uncomment and edit the following line if your project needs to run something other than `rake`:
gemfile:
  Gemfile
script:
  - ruby tests/travisci.rb
  - ./tests/run_foodcritic
